use std::hash::Hash;

use picomint_encoding::{Decodable, Encodable};
use serde::{Deserialize, Serialize};
use tbs::{BlindedMessage, Message};
use thiserror::Error;

use crate::Amount;
use crate::secp256k1::XOnlyPublicKey;

pub mod config;
pub mod methods;

/// Compact representation of a power-of-2 amount denomination
/// Represents 2^denomination msat
#[derive(
    Debug,
    Copy,
    Clone,
    Eq,
    PartialEq,
    Hash,
    Ord,
    PartialOrd,
    Serialize,
    Deserialize,
    Encodable,
    Decodable,
)]
pub struct Denomination(pub u8);

impl Denomination {
    /// Convert to Amount (only call at boundaries)
    pub fn amount(self) -> Amount {
        Amount::from_msat(1 << self.0 as usize)
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintOutputBlindSignature(pub tbs::BlindedSignature);

/// A verifiable one time use IOU from the mint.
///
/// Digital version of a "note of deposit" in a free-banking era.
///
/// Consist of a user-generated nonce and a threshold signature over it
/// generated by the federated mint.
///
/// In this form it can only be validated, not spent since for that the
/// corresponding secret spend key is required.
#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct Note {
    pub denomination: Denomination,
    pub nonce: XOnlyPublicKey,
    pub signature: tbs::Signature,
}

impl Note {
    pub fn amount(&self) -> Amount {
        self.denomination.amount()
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintInput {
    pub note: Note,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintOutput {
    pub denomination: Denomination,
    pub nonce: BlindedMessage,
}

impl MintOutput {
    pub fn amount(&self) -> Amount {
        self.denomination.amount()
    }
}

pub fn verify_note(note: Note, pk: tbs::AggregatePublicKey) -> bool {
    tbs::verify(nonce_message(note.nonce), note.signature, pk)
}

pub fn nonce_message(nonce: XOnlyPublicKey) -> Message {
    tbs::Message::from_public_key(nonce.serialize())
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Error, Encodable, Decodable)]
pub enum MintInputError {
    #[error("The note is already spent")]
    SpentCoin,
    #[error("The note has an invalid amount not issued by the mint")]
    InvalidDenomination,
    #[error("The note has an invalid signature")]
    InvalidSignature,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Error, Encodable, Decodable)]
pub enum MintOutputError {
    #[error("The blinded nonce has already been signed")]
    ReusedNonce,
    #[error("The note has an invalid amount not issued by the mint")]
    InvalidDenomination,
}
