use std::fmt;
use std::hash::Hash;

use bitcoin_hashes::hash160;
use picomint_encoding::{Decodable, Encodable};
use serde::{Deserialize, Serialize};
use tbs::{BlindedMessage, Message};
use thiserror::Error;

use crate::Amount;
use crate::core::ModuleKind;
use crate::secp256k1::PublicKey;

pub mod config;
pub mod endpoint_constants;

pub const KIND: ModuleKind = ModuleKind::Mint;

/// Compact representation of a power-of-2 amount denomination
/// Represents 2^denomination msats
#[derive(
    Debug,
    Copy,
    Clone,
    Eq,
    PartialEq,
    Hash,
    Ord,
    PartialOrd,
    Serialize,
    Deserialize,
    Encodable,
    Decodable,
)]
pub struct Denomination(pub u8);

picomint_redb::consensus_key!(Denomination);

impl Denomination {
    /// Convert to Amount (only call at boundaries)
    pub fn amount(self) -> Amount {
        Amount::from_msats(1 << self.0 as usize)
    }
}

impl fmt::Display for Denomination {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "2^{} msats", self.0)
    }
}

/// The mint module does not define any consensus items.
#[derive(Debug, Clone, Eq, PartialEq, Hash, Serialize, Deserialize, Encodable, Decodable)]
pub enum MintConsensusItem {}

impl std::fmt::Display for MintConsensusItem {
    #[allow(clippy::uninhabited_references)]
    fn fmt(&self, _f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match *self {}
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintOutputBlindSignature(pub tbs::BlindedSignature);

/// A verifiable one time use IOU from the mint.
///
/// Digital version of a "note of deposit" in a free-banking era.
///
/// Consist of a user-generated nonce and a threshold signature over it
/// generated by the federated mint.
///
/// In this form it can only be validated, not spent since for that the
/// corresponding secret spend key is required.
#[derive(Debug, Copy, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct Note {
    pub denomination: Denomination,
    pub nonce: PublicKey,
    pub signature: tbs::Signature,
}

impl Note {
    pub fn amount(&self) -> Amount {
        self.denomination.amount()
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintInput {
    pub note: Note,
}

impl std::fmt::Display for MintInput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Mint Note {}", self.note.denomination)
    }
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct MintOutput {
    pub denomination: Denomination,
    pub nonce: BlindedMessage,
    pub tweak: [u8; 16],
}

impl MintOutput {
    pub fn amount(&self) -> Amount {
        self.denomination.amount()
    }
}

impl std::fmt::Display for MintOutput {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Mint Note {}", self.denomination)
    }
}

/// Recovery item for stateless ecash recovery
#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub enum RecoveryItem {
    Output {
        denomination: Denomination,
        nonce_hash: hash160::Hash,
        tweak: [u8; 16],
    },
    Input {
        nonce_hash: hash160::Hash,
    },
}

picomint_redb::consensus_value!(RecoveryItem);

pub fn verify_note(note: Note, pk: tbs::AggregatePublicKey) -> bool {
    tbs::verify(nonce_message(note.nonce), note.signature, pk)
}

pub fn nonce_message(nonce: PublicKey) -> Message {
    tbs::Message::from_public_key(nonce.serialize())
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Error, Encodable, Decodable)]
pub enum MintInputError {
    #[error("The note is already spent")]
    SpentCoin,
    #[error("The note has an invalid amount not issued by the mint")]
    InvalidDenomination,
    #[error("The note has an invalid signature")]
    InvalidSignature,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Error, Encodable, Decodable)]
pub enum MintOutputError {
    #[error("The note has an invalid amount not issued by the mint")]
    InvalidDenomination,
}
