use bitcoin::hashes::{Hash, hash160, sha256};
use bitcoin::key::{TapTweak, TweakedPublicKey};
use bitcoin::{
    Address, Network, PubkeyHash, ScriptBuf, ScriptHash, Txid, WPubkeyHash, WScriptHash,
};
use picomint_encoding::{Decodable, Encodable};

use secp256k1::{PublicKey, Scalar, XOnlyPublicKey};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use tss::AggregatePublicKey;

pub mod config;
pub mod methods;

pub fn tweak_public_key(pk: &PublicKey, tweak: &sha256::Hash) -> PublicKey {
    pk.add_exp_tweak(
        secp256k1::SECP256K1,
        &Scalar::from_be_bytes(tweak.to_byte_array()).expect("Hash is within field order"),
    )
    .expect("Failed to tweak bitcoin public key")
}

/// The federation's output key for a given tweak. We use the tweaked
/// aggregate key as the taproot output key directly, without a BIP341
/// taptweak: the aggregate key is generated by a hash-committed DKG and the
/// tweak is hash-derived, so no covert script path can exist, and we never
/// spend via script path.
pub fn tweaked_output_key(agg_pk: &AggregatePublicKey, tweak: &sha256::Hash) -> TweakedPublicKey {
    tweak_public_key(&agg_pk.0, tweak)
        .x_only_public_key()
        .0
        .dangerous_assume_tweaked()
}

/// The federation's P2TR script pubkey for a given tweak.
pub fn tweaked_script_pubkey(agg_pk: &AggregatePublicKey, tweak: &sha256::Hash) -> ScriptBuf {
    ScriptBuf::new_p2tr_tweaked(tweaked_output_key(agg_pk, tweak))
}

/// The federation's deposit address for a given tweak.
pub fn tweaked_address(
    agg_pk: &AggregatePublicKey,
    tweak: &sha256::Hash,
    network: Network,
) -> Address {
    Address::p2tr_tweaked(tweaked_output_key(agg_pk, tweak), network)
}

/// Returns true if the script pubkey potentially belongs to the federation.
/// This uses a probabilistic filter - only ~1/65536 of P2WSH scripts pass.
pub fn is_potential_receive(pks_hash: &sha256::Hash, script_pubkey: &ScriptBuf) -> bool {
    (pks_hash, script_pubkey)
        .consensus_hash::<sha256::Hash>()
        .to_byte_array()
        .iter()
        .take(2)
        .all(|b| *b == 0)
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Encodable, Decodable)]
pub struct FederationWallet {
    pub value: bitcoin::Amount,
    pub outpoint: bitcoin::OutPoint,
    pub tweak: sha256::Hash,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Encodable, Decodable)]
pub struct TxInfo {
    pub index: u64,
    pub txid: bitcoin::Txid,
    pub input: bitcoin::Amount,
    pub output: bitcoin::Amount,
    pub fee: bitcoin::Amount,
    pub vbytes: u64,
    pub created: u64,
}

impl TxInfo {
    pub fn feerate(&self) -> u64 {
        self.fee.to_sat() / self.vbytes
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize, Encodable, Decodable)]
pub struct OutputInfo {
    pub index: u64,
    pub script: ScriptBuf,
    pub value: bitcoin::Amount,
    pub spent: bool,
}

#[derive(Clone, Debug, PartialEq, Eq, Hash, Serialize, Deserialize, Encodable, Decodable)]
pub enum WalletConsensusItem {
    BlockCount(u64),
    Feerate(Option<u64>),
    /// One public nonce pair per input of the unsigned transaction - a
    /// peer's first entry into the transaction's append-only nonce log.
    /// Consecutive chunks of threshold entries form the signing sessions.
    Nonces(Txid, Vec<tss::PublicNonce>),
    /// One signature share per input for the signing session formed by the
    /// log chunk containing the peer's latest nonce entry, plus one fresh
    /// nonce pair per input appended to the log. Since a crashed session
    /// member never appends a replacement nonce it is excluded from all
    /// future sessions, so some session completes after at most n - t + 1
    /// attempts as long as a threshold of peers remains live.
    Signatures(Txid, Vec<tss::SignatureShare>, Vec<tss::PublicNonce>),
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct WalletInput {
    pub output_index: u64,
    pub tweak: XOnlyPublicKey,
    pub fee: bitcoin::Amount,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Deserialize, Serialize, Encodable, Decodable)]
pub struct WalletOutput {
    pub destination: StandardScript,
    pub value: bitcoin::Amount,
    pub fee: bitcoin::Amount,
}

#[derive(Debug, Error, Encodable, Decodable, Hash, Clone, Eq, PartialEq)]
pub enum WalletInputError {
    #[error("The output has already been claimed")]
    OutputAlreadySpent,
    #[error("Unknown output index")]
    UnknownOutputIndex,
    #[error("The tweak does not match the output script")]
    WrongTweak,
    #[error("No up to date feerate is available at the moment. Please try again later.")]
    NoConsensusFeerateAvailable,
    #[error("The total transaction fee is too low. Please construct a new transaction.")]
    InsufficientTotalFee,
    #[error("Constructing the pegin transaction caused an arithmetic overflow")]
    ArithmeticOverflow,
    #[error("The federation is already signing a transaction. Please try again later.")]
    PendingTransaction,
}

#[derive(Debug, Error, Encodable, Decodable, Hash, Clone, Eq, PartialEq)]
pub enum WalletOutputError {
    #[error("The output value is below the dust limit.")]
    UnderDustLimit,
    #[error("The federation does not have any funds yet")]
    NoFederationUTXO,
    #[error("No up to date feerate is available at the moment. Please try again later.")]
    NoConsensusFeerateAvailable,
    #[error("The total transaction fee is too low. Please construct a new transaction.")]
    InsufficientTotalFee,
    #[error("The change value is below the dust limit.")]
    ChangeUnderDustLimit,
    #[error("Constructing the pegout transaction caused an arithmetic overflow")]
    ArithmeticOverflow,
    #[error("The federation is already signing a transaction. Please try again later.")]
    PendingTransaction,
}

#[derive(Debug, Clone, Eq, PartialEq, Hash, Encodable, Decodable, Serialize, Deserialize)]
pub enum StandardScript {
    P2PKH(hash160::Hash),
    P2SH(hash160::Hash),
    P2WPKH(hash160::Hash),
    P2WSH(sha256::Hash),
    P2TR(XOnlyPublicKey),
}

impl StandardScript {
    pub fn from_address(address: &Address) -> Option<Self> {
        if let Some(hash) = address.pubkey_hash() {
            return Some(Self::P2PKH(hash.to_raw_hash()));
        }

        if let Some(hash) = address.script_hash() {
            return Some(Self::P2SH(hash.to_raw_hash()));
        }

        let program = address.witness_program()?;

        if program.is_p2wpkh() {
            return Some(Self::P2WPKH(
                hash160::Hash::from_slice(program.program().as_bytes())
                    .expect("Witness program is 20 bytes"),
            ));
        }

        if program.is_p2wsh() {
            return Some(Self::P2WSH(
                sha256::Hash::from_slice(program.program().as_bytes())
                    .expect("Witness program is 32 bytes"),
            ));
        }

        if program.is_p2tr() {
            return Some(Self::P2TR(
                XOnlyPublicKey::from_slice(program.program().as_bytes())
                    .expect("Witness program is 32 bytes"),
            ));
        }

        None
    }

    pub fn script_pubkey(&self) -> ScriptBuf {
        match self {
            Self::P2PKH(hash) => ScriptBuf::new_p2pkh(&PubkeyHash::from_raw_hash(*hash)),
            Self::P2SH(hash) => ScriptBuf::new_p2sh(&ScriptHash::from_raw_hash(*hash)),
            Self::P2WPKH(hash) => ScriptBuf::new_p2wpkh(&WPubkeyHash::from_raw_hash(*hash)),
            Self::P2WSH(hash) => ScriptBuf::new_p2wsh(&WScriptHash::from_raw_hash(*hash)),
            Self::P2TR(pk) => ScriptBuf::new_p2tr_tweaked(pk.dangerous_assume_tweaked()),
        }
    }
}

#[cfg(test)]
fn assert_standard_script_roundtrip(addr: &str, variant: fn(&StandardScript) -> bool) {
    let address = addr
        .parse::<bitcoin::Address<bitcoin::address::NetworkUnchecked>>()
        .expect("Failed to parse address")
        .require_network(bitcoin::Network::Bitcoin)
        .expect("Wrong network");

    let script = StandardScript::from_address(&address)
        .expect("Failed to convert address to StandardScript");

    assert!(variant(&script), "Unexpected StandardScript variant");

    assert_eq!(address.script_pubkey(), script.script_pubkey());
}

#[test]
fn test_standard_script_p2pkh() {
    assert_standard_script_roundtrip("1QJVDzdqb1VpbDK7uDeyVXy9mR27CJiyhY", |s| {
        matches!(s, StandardScript::P2PKH(..))
    });
}

#[test]
fn test_standard_script_p2sh() {
    assert_standard_script_roundtrip("33iFwdLuRpW1uK1RTRqsoi8rR4NpDzk66k", |s| {
        matches!(s, StandardScript::P2SH(..))
    });
}

#[test]
fn test_standard_script_p2wpkh() {
    assert_standard_script_roundtrip("bc1qvzvkjn4q3nszqxrv3nraga2r822xjty3ykvkuw", |s| {
        matches!(s, StandardScript::P2WPKH(..))
    });
}

#[test]
fn test_standard_script_p2wsh() {
    assert_standard_script_roundtrip(
        "bc1qwqdg6squsna38e46795at95yu9atm8azzmyvckulcc7kytlcckxswvvzej",
        |s| matches!(s, StandardScript::P2WSH(..)),
    );
}

#[test]
fn test_standard_script_p2tr() {
    assert_standard_script_roundtrip(
        "bc1p5cyxnuxmeuwuvkwfem96lqzszd02n6xdcjrs20cac6yqjjwudpxqkedrcr",
        |s| matches!(s, StandardScript::P2TR(..)),
    );
}

#[test]
fn test_standard_script_unknown_witness_version() {
    let address = "bc1pw508d6qejxtdg4y5r3zarvary0c5xw7kw508d6qejxtdg4y5r3zarvary0c5xw7kt5nd6y"
        .parse::<bitcoin::Address<bitcoin::address::NetworkUnchecked>>()
        .expect("Failed to parse address")
        .require_network(bitcoin::Network::Bitcoin)
        .expect("Wrong network");

    assert!(StandardScript::from_address(&address).is_none());
}
