[package]
authors = { workspace = true }
description = "Shared types for picomint-node admin CLI"
edition = { workspace = true }
license = { workspace = true }
name = "picomint-node-cli-core"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["serde"] }
clap = { workspace = true }
picomint-core = { workspace = true }
thiserror = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
tss = { workspace = true }
