[package]
authors = { workspace = true }
description = "picomint-sqlite provides a SQLite-backed database implementation for Picomint."
edition = { workspace = true }
license = { workspace = true }
name = "picomint-sqlite"
readme = { workspace = true }
repository = { workspace = true }
version = { workspace = true }

[lib]
name = "picomint_sqlite"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
picomint-encoding = { workspace = true }
rusqlite = { workspace = true }
tokio = { workspace = true, features = ["sync", "rt"] }

[dev-dependencies]
tempfile = { workspace = true }
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
