[package]
name = "picomint-broker-cli"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Admin CLI for the picomint broker daemon"

[dependencies]
clap = { workspace = true }
picomint-analytics = { workspace = true }
picomint-broker-cli-core = { workspace = true }
picomint-cli-client = { workspace = true }
picomint-client = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt"] }
